localChrome = "/Users/jianjia/Documents/projects/mini-app/MiniScope/drivers/116"
appName = "遂川旅游景点"
appID = "wx4938079035028687"

[capabilities]
deviceName = "Pixel_6a"
platformName = "Android"
appPackage = "com.tencent.mm"
appActivity = "com.tencent.mm.ui.LauncherUI"
automationName = "uiautomator2"
noReset = true
unicodeKeyboard = true
resetKeyboard = true
chromedriverExecutable = "/Users/jianjia/Documents/projects/mini-app/MiniScope/drivers/116"
