localChrome = "/Users/jianjia/Documents/projects/mini-app/MiniScope/drivers/116"
appName = "美团丨外卖团购特价美食酒店电影,"
appID = "wxde8ac0a21135c07d"

[capabilities]
deviceName = "*"
platformName = "Android"
appPackage = "com.tencent.mm"
appActivity = "com.tencent.mm.ui.LauncherUI"
automationName = "uiautomator2"
noReset = true
unicodeKeyboard = true
resetKeyboard = true
chromedriverExecutable = "/Users/jianjia/Documents/projects/mini-app/MiniScope/drivers/116"
